version: '3.3'
# maintainer: "SEVENDI ELDRIGE RIFKI POLUAN <sevendipoluan@gmail.com>"

services:   
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15 
    container_name: mqtt-broker
    restart: always 
    deploy:
      replicas: 1
    ports:
      - "1883:1883"
    privileged: true
    volumes:
      - ${PWD}/mosquitto/:/mosquitto/